Module3 task1
htmlacademy-ecmascript/982629-cinemaddict-15 pull request #5
Opened 2021-08-07 19:25 UTC by dimkinx

2021-08-08 19:07 UTC, dtsaryov requested changes

2021-08-08 19:07 UTC, dtsaryov commented on src/view/statistics.js
> +export default class StatisticsView {
Б27. Название модуля соответствует его содержимому.

2021-08-08 19:07 UTC, dtsaryov commented on src/view/statistics.js
> +  constructor(films) {
Здесь нужно только количество фильмов

2021-08-08 19:07 UTC, dtsaryov commented on src/view/show-more-button.js
> +export default class ShowMoreButtonView {
Б27. Название модуля соответствует его содержимому.

2021-08-08 19:07 UTC, dtsaryov commented on src/view/profile.js
> +export default class ProfileView {
Б27. Название модуля соответствует его содержимому.

2021-08-08 19:07 UTC, dtsaryov commented on src/view/menu.js
> +export default class MenuView {
Б27. Название модуля соответствует его содержимому.

2021-08-08 19:07 UTC, dtsaryov commented on src/view/films.js
> +export default class FilmsSectionView {
Б27. Название модуля соответствует его содержимому.

2021-08-08 19:07 UTC, dtsaryov commented on src/view/films-extra.js
> +export default class FilmsExtraView {
Б27. Название модуля соответствует его содержимому.

2021-08-08 19:07 UTC, dtsaryov commented on src/view/film.js
> +export default class FilmCardView {
Б27. Название модуля соответствует его содержимому.

2021-08-08 19:07 UTC, dtsaryov commented on src/view/details.js
> +export default class FilmDetailsView {
Б27. Название модуля соответствует его содержимому.

2021-08-08 19:07 UTC, dtsaryov commented on src/main.js
> +  filmCardComponent.getElement().querySelector('.film-card__comments').addEventListener('click', filmCardClickHandler);
Строго говоря, в этом случае применим критерий

Д26. Операции над DOM-элементами инкапсулированы.

Правильно будет добавить метод классу, который принимает коллбэк, и внутри добавляет слушатель, который при срабатывании вызывает переданный коллбэк

2021-08-09 07:11 UTC, dimkinx commented on src/main.js
> +  filmCardComponent.getElement().querySelector('.film-card__comments').addEventListener('click', filmCardClickHandler);
...сегодня в завтрашний день, не все могут смотреть...

2021-08-09 16:02 UTC, dtsaryov approved these changes

2021-08-09 16:02 UTC, merged