Module5 task1
htmlacademy-ecmascript/982629-cinemaddict-15 pull request #8
Opened 2021-08-18 01:19 UTC by dimkinx

2021-08-18 17:50 UTC, dtsaryov requested changes

2021-08-18 17:50 UTC, dtsaryov commented on src/view/film-details-view.js
> +  setWatchlistButtonClickHandler(callback) {
Д8. Методы внутри классов упорядочены.

Проверь везде на соответствие критерию

2021-08-18 17:50 UTC, dtsaryov commented on src/view/films-empty-view.js
> +export default class FilmsEmptyView extends AbstractView {
Не надо еще один компонент делать. Просто расширь функционал FilmsView

2021-08-18 17:50 UTC, dtsaryov commented on src/presenter/films-presenter.js
> +const NavigationType = {
Это называется фильтры

https://up.htmlacademy.ru/ecmascript/15/project/cinemaddict#filters

2021-08-18 17:50 UTC, dtsaryov commented on src/presenter/films-presenter.js
> +const FilmsExtraType = {
ExtraList

2021-08-18 17:50 UTC, dtsaryov commented on src/presenter/films-presenter.js
> +  TOP_RATED: 'TopRated',
Почему бы в качестве значения не использовать человеческий заголовок, который будет отображаться на странице?

2021-08-18 17:50 UTC, dtsaryov commented on src/presenter/films-presenter.js
> +const navigations = [
Это должно быть перечислением

2021-08-18 17:50 UTC, dtsaryov commented on src/presenter/films-presenter.js
> +    sort: (filmsData) => filmsData
Слово Data здесь не нужно. И старайся не использовать его нигде

2021-08-18 17:50 UTC, dtsaryov commented on src/presenter/films-presenter.js
> +const filmsExtra = [
Почему бы не сделать сложносоставное перечисление?

```JS

const ExtraList = {
  TOP_RATED: {
    name: 'Top rated',
    getFilms: (films) => {films.slice().sort().slice();}
  },
  MOST_COMMENTED: {
    // ...
  }
};
```

2021-08-18 17:50 UTC, dtsaryov commented on src/presenter/films-presenter.js
> +const updateItem = (items, update) => {
Сразу в utils можно вынести

2021-08-18 17:50 UTC, dtsaryov commented on src/presenter/films-presenter.js
> +    this._filmsExtra = filmsExtra;
Это поле можно не объявлять

2021-08-18 17:50 UTC, dtsaryov commented on src/presenter/films-presenter.js
> +    this._footerContainer = footerContainer;
Не надо футер передавать через всю цепочку. Попап рендерится просто в body - вот и давай рендерить туда

2021-08-18 17:50 UTC, dtsaryov commented on src/presenter/films-presenter.js
> +    this._comments = comments;
А почему комменты не копируем?

2021-08-18 17:50 UTC, dtsaryov commented on src/presenter/films-presenter.js
> +      this._filmPresenter.get(updatedFilm.id).init(updatedFilm, this._comments[updatedFilm.id]);
Два раза ищешь значение по ключу. Вместо этого делай get и проверяй на результат

2021-08-18 17:50 UTC, dtsaryov commented on src/presenter/films-presenter.js
> +    if (this._filmDetailsPresenter && this._filmDetailsPresenter.id === updatedFilm.id) {
FilmsPresenter не должен этим управлять. Для этого у нас должен быть презентер, который управляет и обычной карточкой и попапом

2021-08-18 17:50 UTC, dtsaryov commented on src/presenter/film-presenter.js
> +    this._openModal = openModal;
FilmPresenter должен сам рендерить и карточку, и попап

2021-08-22 17:02 UTC, dimkinx commented
Uploading simplescreenrecorder-2021-08-22_19.58.26.mp4…

2021-08-23 18:27 UTC, merged